import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    'auth.store': 'src/auth.store.ts',
    'onboarding.store': 'src/onboarding.store.ts',
    'health.store': 'src/health.store.ts',
    'iap.store': 'src/iap.store.ts',
    'dialog.store': 'src/dialog.store.ts',
    'admin.store': 'src/admin.store.ts',
    'ai-models.store': 'src/ai-models.store.ts',
    'ai-settings.store': 'src/ai-settings.store.ts',
    'body-measurements.hooks': 'src/body-measurements.hooks.ts',
    'body-measurements.store': 'src/body-measurements.store.ts',
    'catalog.store': 'src/catalog.store.ts',
    'chat.store': 'src/chat.store.ts',
    'copilot.store': 'src/copilot.store.ts',
    'copilot-active-context.store': 'src/copilot-active-context.store.ts',
    'direct-messaging.hooks': 'src/direct-messaging.hooks.ts',
    'header-actions.store': 'src/header-actions.store.ts',
    'maxes.store': 'src/maxes.store.ts',
    'navigation-state.store': 'src/navigation-state.store.ts',
    'oneagenda.store': 'src/oneagenda.store.ts',
    'realtime.hooks': 'src/realtime.hooks.ts',
    'realtime.store': 'src/realtime.store.ts',
    'sidebar.store': 'src/sidebar.store.ts',
    'storage.native': 'src/storage.native.ts',
    'ui.store': 'src/ui.store.ts',
    'versioning.store': 'src/versioning.store.ts',
    'workout-builder.store': 'src/workout-builder.store.ts',
  },
  format: ['esm', 'cjs'],
  dts: true,
  sourcemap: true,
  clean: true,
  shims: true,
});
