import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    'config/env': 'src/config/env.ts',
    prisma: 'src/prisma.ts',
    db: 'src/db.ts',
    'logger.service': 'src/logger.service.ts',
    'direct-messaging.service': 'src/direct-messaging.service.ts',
    'user-memory.service': 'src/user-memory.service.ts',
    'user-memory/types': 'src/user-memory/types.ts',
    'user-memory/listeners': 'src/user-memory/listeners.ts',
    'user-memory/timeline.service': 'src/user-memory/timeline.service.ts',
    'auth/index': 'src/auth/index.ts',
    'auth/session': 'src/auth/session.ts',
    'auth/session.native': 'src/auth/session.native.ts',
    'auth/guards': 'src/auth/guards.ts',
    'auth/roles': 'src/auth/roles.ts',
    'auth/config': 'src/auth/config.ts',
    'auth/admin-seed': 'src/auth/admin-seed.ts',
    'types/safe-types': 'src/types/safe-types.ts',
    'types/calendar.client-types': 'src/types/calendar.client-types.ts',
    stripe: 'src/stripe.ts',
    'stripe/index': 'src/stripe/index.ts',
    'stripe/client': 'src/stripe/client.ts',
    'stripe/config': 'src/stripe/config.ts',
    'credit.service': 'src/credit.service.ts',
    'subscription.service': 'src/subscription.service.ts',
    'user-profile.service': 'src/user-profile.service.ts',
    'payment.service': 'src/payment.service.ts',
    'onboarding.service': 'src/onboarding.service.ts',
    'calendar.service': 'src/calendar.service.ts',
    'invitation.service': 'src/invitation.service.ts',
    'consent.service': 'src/consent.service.ts',
    'policy.service': 'src/policy.service.ts',
    'setup-intent.service': 'src/setup-intent.service.ts',
    'user/onboarding-profile.service': 'src/user/onboarding-profile.service.ts',
    'edge-config.service': 'src/edge-config.service.ts',
    'feature-flags.service': 'src/feature-flags.service.ts',
    'feature-flags.evaluator': 'src/feature-flags.evaluator.ts',
    'ai/provider-factory': 'src/ai/provider-factory.ts',
    'iap-verification.server': 'src/iap-verification.server.ts',
    'versioning/index': 'src/versioning/index.ts',
    'versioning/create-versioning-actions': 'src/versioning/create-versioning-actions.ts',
  },
  format: ['esm', 'cjs'],
  dts: true,
  clean: true,
  treeshake: true,
  sourcemap: true,
  outDir: 'dist',
  splitting: true,
  external: [
    /^@giulio-leone\//,
    '@prisma/client',
    'zod',
    /^date-fns/,
    /^next/,
    /^react/,
    /^expo/,
    /^@react-native/,
    'react-native',
  ],
});
